// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PQCLession12.Models;

#nullable disable

namespace PQCLession12.Migrations
{
    [DbContext(typeof(PqcAppDbContext))]
    partial class PqcAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PQCLession12.Models.PqcCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PqcCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PqcName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte>("PqcStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("PqcCategory");
                });

            modelBuilder.Entity("PQCLession12.Models.PqcProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PqcCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PqcCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PqcDescriptions")
                        .HasMaxLength(1000)
                        .HasColumnType("ntext");

                    b.Property<string>("PqcImage")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PqcName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<float>("PqcPrice")
                        .HasColumnType("real");

                    b.Property<float>("PqcSalePrice")
                        .HasColumnType("real");

                    b.Property<byte>("PqcStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PqcCategoryId");

                    b.ToTable("PqcProduct");
                });

            modelBuilder.Entity("PQCLession12.Models.PqcProduct", b =>
                {
                    b.HasOne("PQCLession12.Models.PqcCategory", "PqcCategory")
                        .WithMany("PqcProducts")
                        .HasForeignKey("PqcCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PqcCategory");
                });

            modelBuilder.Entity("PQCLession12.Models.PqcCategory", b =>
                {
                    b.Navigation("PqcProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
